version: '3.4'


services:
  postgres:
    container_name: hamburgueria
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hamburgueria
    volumes:
      - ./data:/data/postgres
    ports:
    - "5432-5432"
