version: '3.4'

services:
  postgres:
    container_name: hamburguer
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hamburguer
    volumes:
      - ./data:/data/postgres
    ports:
    - "5432-5432"
